apiVersion: v1
kind: Service
metadata:
  name: ${project.artifactId}
  labels:
    expose: true
    run: ${project.artifactId}
spec:
  type: NodePort
  ports:
    - port: 8090
      nodePort: 30880
  selector:
    name: ${project.artifactId}
