apiVersion: v1
kind: Service
metadata:
  name: ${project.artifactId}
  labels:
    expose: true
    run: ${project.artifactId}
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: ${docker.http.port}
      nodePort: ${kubernetes.http.port}
    - name: https
      protocol: TCP
      port: ${docker.https.port}
      nodePort: ${kubernetes.https.port}
  selector:
    name: ${project.artifactId}
